require('settings')
require('plugins')
require('colors')
require('nvim-tree-config')
require('mappings')
require('lsp-config')
require('lsp-config.nvim-cmp')
require('dashboard-config')
vim.cmd('let g:neovide_transparency=0.6')
vim.cmd('let g:user_emmet_leader_key=","')
vim.cmd("let g:vimwiki_list = [{'path': '~/documents/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]")

